### ISSUE TITLE
UnboundLocalError - SAM

### ISSUE THREAD

**Issue by etwatson** [mjsull/DiscoPlot#2]
I get the following error when I attempt to use a SAM file:

```
dobzhansky@muller: python DiscoPlot.py -sam AB_bbmap.sam -s 5000
Traceback (most recent call last):
  File "/usr/share/DiscoPlot/discoplot/DiscoPlot.py", line 535, in <module>
    read_sbam(args)
  File "/usr/share/DiscoPlot/discoplot/DiscoPlot.py", line 81, in read_sbam
    references = sam.references
UnboundLocalError: local variable 'sam' referenced before assignment
```

**Comment by mjsull** [comment]
Hi,

Sorry for taking so long to get back to you. I think this is fixed in the most recent version.

Best,

Mitchell
