### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Estherrr1997** [mjsull/DiscoPlot#3]
Hi,

I tried installing DiscoPlot but I get this error:

(base) admin_bi@GSYMK2:/media/admin_bi/DATA/Files_Esther/DiscoPlot-1.0.2$ pip install --user DiscoPlot
Collecting DiscoPlot
  Using cached DiscoPlot-1.0.2.tar.gz (94 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-bgx_l9ih/discoplot_13b996cbcb58403597de3b024e27c986/setup.py", line 11
          print "Installation of DiscoPlot requires pip. Please install it! See -"
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Installation of DiscoPlot requires pip. Please install it! See -")?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Although pip is installed:
(base) admin_bi@GSYMK2:/media/admin_bi/DATA/Files_Esther/DiscoPlot-1.0.2$ pip

Usage:   
  pip <command> [options]

Do you know how to fix this?

**Comment by mjsull** [comment]
Hi,

Discoplot was written in Python2.7 so you will need pip2 to install it.

Best,

Mitch

**Comment by Estherrr1997** [comment]
Thank you, I installed pip2 and tried to install DiscoPlot.
The command I use:
(base) admin_bi@GSYMK2:/media/admin_bi/DATA/Files_Esther/DiscoPlot-1.0.2$ pip2 install --user DiscoPlot

After this, I get a very long error message:
[error_message_20-04.txt](https://github.com/mjsull/DiscoPlot/files/8521035/error_message_20-04.txt)

What can I do to fix this?

**Comment by Estherrr1997** [comment]
I still haven't figured out what causes the error, I do have DiscoPlot installed:

(base) admin_bi@GSYMK2:/media/admin_bi/DATA/Files_Esther/DiscoPlot-1.0.2/discoplot$ ls
argparse  DiscoPlot  DiscoPlot.py  __init__.py  numpy  random  subprocess  sys
(base) admin_bi@GSYMK2:/media/admin_bi/DATA/Files_Esther/DiscoPlot-1.0.2/discoplot$ cd ..
(base) admin_bi@GSYMK2:/media/admin_bi/DATA/Files_Esther/DiscoPlot-1.0.2$ ls
CITATION.txt  discoplot  docs  do_release.sh  error_message_20-04  get-pip.py  LICENSE  MANIFEST.in  pictures  README.rst  requirements-dev.txt  requirements.txt  setup.py  tests

But checking the installation outputs:
(base) admin_bi@GSYMK2:/media/admin_bi/DATA/Files_Esther/DiscoPlot-1.0.2$ DiscoPlot -h
DiscoPlot: command not found

And the "pip install --user DiscoPlot" still gives the same error as mentioned in my last comment. 
How can I use DiscoPlot? Is the pip install command still needed when DiscoPlot is already installed?

Really hope you can help me with this! :)

**Comment by mjsull** [comment]
Hi, it will probably run fine with `python2.7 /full/path/to/DiscoPlot.py`

Haha, sorry it's been a very long time since I've looked at this.
